name: local_auth_windows
publish_to: none
description: Windows implementation of the local_auth plugin.
repository: https://github.com/flutter/packages/tree/main/packages/local_auth/local_auth_windows
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+local_auth%22
version: 1.0.11

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

flutter:
  plugin:
    implements: local_auth
    platforms:
      windows:
        pluginClass: LocalAuthPlugin
        dartPluginClass: LocalAuthWindows

dependencies:
  flutter:
    sdk: flutter
  local_auth_platform_interface:
    git: https://github.com/kumsumit/local_auth_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^25.3.2

topics:
  - authentication
  - biometrics
  - local-auth
